import { parse } from "yaml";
import { print } from "../output/format.js";
import { readPackageFile } from "./files.js";
import { type GlobalOptions, outputOptions, type RuntimeDependencies } from "./runtime.js";

export type CompletionShell = "bash" | "zsh" | "fish" | "powershell";

type OcsOption = {
  name: string;
  aliases?: string[];
};

type OcsCommand = {
  name: string;
  options?: OcsOption[];
  commands?: OcsCommand[];
};

export async function runCompletion(
  shell: CompletionShell,
  globals: GlobalOptions,
  deps: RuntimeDependencies = {},
): Promise<void> {
  const document = parse(await readPackageFile("cli.ocs.yaml", import.meta.url)) as {
    command: OcsCommand;
  };
  const words = Array.from(
    new Set([...commandWords(document.command), ...optionWords(document.command)]),
  );
  const script = renderCompletion(shell, words);

  if (globals.json || globals.raw) {
    print(script, outputOptions(globals, deps));
    return;
  }

  (deps.streams?.stdout ?? process.stdout).write(script);
}

function renderCompletion(shell: CompletionShell, values: string[]): string {
  if (shell === "bash") {
    return bash(values);
  }
  if (shell === "zsh") {
    return zsh(values);
  }
  if (shell === "fish") {
    return fish(values);
  }
  return powershell(values);
}

function commandWords(command: OcsCommand): string[] {
  return [command.name, ...(command.commands ?? []).flatMap(commandWords)];
}

function optionWords(command: OcsCommand): string[] {
  return [
    ...(command.options ?? []).flatMap((option) => [option.name, ...(option.aliases ?? [])]),
    ...(command.commands ?? []).flatMap(optionWords),
  ];
}

function shellWords(values: string[]): string {
  return values.map((value) => value.replace(/'/g, "'\\''")).join(" ");
}

function bash(values: string[]): string {
  return [
    "# Generated by eprospera.",
    "_eprospera_completions() {",
    "  local cur",
    `  cur="\${COMP_WORDS[COMP_CWORD]}"`,
    `  COMPREPLY=( $(compgen -W '${shellWords(values)}' -- "$cur") )`,
    "}",
    "complete -F _eprospera_completions eprospera",
    "",
  ].join("\n");
}

function zsh(values: string[]): string {
  return [
    "#compdef eprospera",
    "# Generated by eprospera.",
    `local -a commands=(${values.map((value) => `"${value}"`).join(" ")})`,
    "_describe 'eprospera command' commands",
    "",
  ].join("\n");
}

function fish(values: string[]): string {
  return [
    "# Generated by eprospera.",
    `complete -c eprospera -f -a '${shellWords(values)}'`,
    "",
  ].join("\n");
}

function powershell(values: string[]): string {
  const quoted = values.map((value) => `'${value.replace(/'/g, "''")}'`).join(", ");
  return [
    "# Generated by eprospera.",
    "Register-ArgumentCompleter -Native -CommandName eprospera -ScriptBlock {",
    "  param($wordToComplete)",
    `  ${quoted} | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {`,
    "    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)",
    "  }",
    "}",
    "",
  ].join("\n");
}
