/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/verify_rpn": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Verify whether an RPN exists and is active
     * @description Rate-limited to 5,000 requests / 24 h and 50 / minute per API key.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @example 80000000000012 */
            rpn: string;
          };
        };
      };
      responses: {
        /** @description Lookup result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {string} */
              result: "found_legal_entity" | "found_natural_person" | "not_found";
              active: boolean;
            };
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        429: components["responses"]["RateLimited"];
        500: components["responses"]["InternalError"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/registries/legal_entities/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Free-text search of the legal-entity registry
     * @description Multi-word queries split on whitespace. Case-insensitive name match plus partial RPN match.
     *     Rate-limited to 5,000 / 24 h and 50 / minute per API key.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @example Acme Holdings */
            query: string;
          };
        };
      };
      responses: {
        /** @description Matching legal entities */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              results?: {
                /** Format: uuid */
                id?: string;
                name?: string;
                extension?: string;
                residentPermitNumber?: string | null;
              }[];
            };
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        429: components["responses"]["RateLimited"];
        500: components["responses"]["InternalError"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/legal_entities/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Fetch one legal entity
     * @description Agent Keys can only access entities whose underlying residency application
     *     was created via the API (`residencyApplication.createdViaAPI === true`).
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["LegalEntityId"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The legal-entity record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data?: components["schemas"]["LegalEntity"];
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        500: components["responses"]["InternalError"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/legal_entities/{id}/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List documents for a legal entity
     * @description Not currently paginated — full result set is returned under `data`.
     *     See https://portal.eprospera.com/api-docs/conventions#pagination.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["LegalEntityId"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Documents for the entity */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data?: components["schemas"]["Document"][];
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        500: components["responses"]["InternalError"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/legal_entity_applications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List legal-entity applications
     * @description Agent Keys see only API-created applications (`createdViaAPI=true`).
     *     Not currently paginated.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Applications visible to the caller */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data?: components["schemas"]["LegalEntityApplication"][];
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        500: components["responses"]["InternalError"];
      };
    };
    put?: never;
    /**
     * Create a legal-entity application
     * @description Write Agent Keys require an active Manifestation of Will. With AOC pre-acceptance
     *     the application auto-progresses on payment; otherwise `nextSteps.signature` returns
     *     a browser URL the human must visit.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateLegalEntityApplicationRequest"];
        };
      };
      responses: {
        /** @description Application created */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data?: components["schemas"]["LegalEntityApplication"];
              nextSteps?: {
                /** Format: uri */
                signature?: string | null;
              };
            };
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        409: components["responses"]["Conflict"];
        500: components["responses"]["InternalError"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/legal_entity_applications/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch one application */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["ApplicationId"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Application */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data?: components["schemas"]["LegalEntityApplication"];
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
        500: components["responses"]["InternalError"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/legal_entity_applications/{id}/pay/coupon": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply a coupon that fully covers the invoice */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["ApplicationId"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            couponCode: string;
          };
        };
      };
      responses: {
        /** @description Coupon applied */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              success?: boolean;
              data?: components["schemas"]["LegalEntityApplication"];
              message?: string;
            };
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        409: components["responses"]["Conflict"];
        500: components["responses"]["InternalError"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/legal_entity_applications/{id}/checkout_session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a hosted-checkout session for the application invoice
     * @description Standard API keys only. Agent Key hosted-checkout creation is temporarily disabled;
     *     use the coupon-payment endpoint or have the resident pay through the portal.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["ApplicationId"];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            paymentProvider: "stripe" | "stripe-crypto" | "lnbits" | "solana-pay-ptc";
            /** Format: uri */
            redirectUrl: string;
            /** Format: email */
            email?: string | null;
          };
        };
      };
      responses: {
        /** @description Checkout session created */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data?: {
                /** Format: uri */
                url?: string;
              };
              /** Format: uuid */
              invoiceId?: string;
            };
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
        500: components["responses"]["InternalError"];
        /** @description Agent Key checkout sessions are temporarily disabled */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error?: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/referral-codes/{code}/referrals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List referrals for a code you own
     * @description Standard API keys only — Agent Keys are not supported on this route.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          code: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Referral attribution */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code?: string;
              naturalPersons?: {
                fullName?: string | null;
                /** Format: date-time */
                referredAt?: string;
              }[];
              legalEntities?: {
                name?: string;
                rpn?: string;
                /** Format: date-time */
                referredAt?: string | null;
              }[];
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
        500: components["responses"]["InternalError"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/natural-person": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Personal details for the authenticated user
     * @description Accepts OAuth tokens (with `eprospera:person.details.read`) and Agent Keys
     *     (with `agent:person.details.read`). Standard API keys are NOT accepted here.
     *     Returns `null` if the owner has no approved residency.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Personal details, or null */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["NaturalPerson"] | null;
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        500: components["responses"]["InternalError"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/natural-person/id-verification": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** ID-verification artifacts (signed URLs, ~1 h TTL) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ID verification record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["IdVerification"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        500: components["responses"]["InternalError"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/natural-person/residency": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Residency status for the authenticated user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Residency status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              wasEverResident?: boolean;
              activeResidency?: {
                /** Format: date-time */
                effectiveDate?: string;
                /** Format: date-time */
                terminationDate?: string | null;
                /** @enum {string} */
                residencyType?: "Limited e-Resident" | "e-Resident" | "Resident";
                version?: string;
              } | null;
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        500: components["responses"]["InternalError"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/legal-entities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the user's consented legal entities (OAuth only) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Legal entities the user consented to share */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data?: components["schemas"]["LegalEntitySummary"][];
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        500: components["responses"]["InternalError"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/legal-entities/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch one consented legal entity (OAuth only) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["LegalEntityId"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The legal-entity record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data?: components["schemas"]["LegalEntity"];
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
        500: components["responses"]["InternalError"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/legal-entities/{id}/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List documents for a consented legal entity (OAuth only) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components["parameters"]["LegalEntityId"];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Documents */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data?: components["schemas"]["Document"][];
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
        500: components["responses"]["InternalError"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/oauth/authorize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** OAuth 2.0 authorization endpoint (RFC 6749 §4.1) */
    get: {
      parameters: {
        query: {
          client_id: string;
          redirect_uri: string;
          response_type: "code";
          scope: string;
          state: string;
          /** @description Required when `openid` is in `scope`. */
          nonce?: string;
          response_mode?: "query" | "fragment" | "form_post";
          code_challenge?: string;
          code_challenge_method?: "S256";
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /**
         * @description Redirects to the consent screen, then to `redirect_uri` with `code` and `state`
         *     (or `error=access_denied&state=...` on denial).
         */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/oauth/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** OAuth 2.0 token endpoint */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/x-www-form-urlencoded":
            | {
                /** @enum {string} */
                grant_type: "authorization_code";
                code: string;
                /** Format: uri */
                redirect_uri: string;
                code_verifier?: string;
                client_id?: string;
                client_secret?: string;
              }
            | {
                /** @enum {string} */
                grant_type: "refresh_token";
                refresh_token: string;
                scope?: string;
                client_id?: string;
                client_secret?: string;
              };
        };
      };
      responses: {
        /** @description Token response (RFC 6749 §5.1) */
        200: {
          headers: {
            "Cache-Control"?: "no-store";
            Pragma?: "no-cache";
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              access_token: string;
              /** @enum {string} */
              token_type: "Bearer";
              /** @example 3600 */
              expires_in: number;
              scope: string;
              id_token?: string;
              refresh_token?: string;
            };
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        500: components["responses"]["InternalError"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/oauth/userinfo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** OIDC userinfo endpoint */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Userinfo claims (subset depends on granted scopes) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              sub: string;
              name?: string | null;
              given_name?: string | null;
              family_name?: string | null;
              /** Format: uri */
              picture?: string | null;
              /** Format: email */
              email?: string | null;
              email_verified?: boolean;
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorEnvelope: {
      error: string;
      error_description?: string;
      details?: Record<string, never>[];
    };
    Address: {
      country?: string;
      line1?: string;
      line2?: string | null;
      city?: string;
      state?: string | null;
      postalCode?: string;
    };
    LegalEntitySummary: {
      /** Format: uuid */
      id?: string;
      /** @example llc */
      optionId?: string;
      /** @example Limited Liability Company */
      type?: string;
      name?: string;
      extension?: string;
      nameStartsWithExtension?: boolean;
      residentPermitNumber?: string | null;
    };
    LegalEntity: components["schemas"]["LegalEntitySummary"] & {
      /** Format: date-time */
      formationDate?: string | null;
      /** Format: date-time */
      registrationDate?: string | null;
      /** Format: date-time */
      dissolutionDate?: string | null;
      /** Format: date-time */
      createdAt?: string;
      principalOfficeAddress?: components["schemas"]["Address"] | null;
    };
    Document: {
      /** Format: uuid */
      id?: string;
      name?: string;
      slug?: string | null;
      version?: string | number;
      /** Format: uri */
      fileUrl?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    LegalEntityApplication: {
      /** Format: uuid */
      id?: string;
      /** @enum {string} */
      statusId?: "Draft" | "Pending Review" | "Approved" | "Rejected";
      /** @description Stored internal format. Not the same shape as the create body. */
      applicationData?: Record<string, never>;
      applicationVersion?: string;
      /** Format: date-time */
      submittedAt?: string | null;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      approvedAt?: string | null;
      /** Format: date-time */
      rejectedAt?: string | null;
      /** Format: uuid */
      legalEntityId?: string | null;
    };
    CreateLegalEntityApplicationRequest: {
      applicationData: {
        /** @enum {string} */
        residencyType: "e-Resident" | "Resident";
        /** @enum {string} */
        entityType: "llc";
        name: string;
        /** @enum {string} */
        extension:
          | "LLC"
          | "L.L.C."
          | "Limited Liability Company"
          | "S. de R.L."
          | "SRL"
          | "Limited Company"
          | "L.C."
          | "LC"
          | "Limited Liability Co."
          | "Limited Co."
          | "Ltd. Co.";
        principalOffice: components["schemas"]["Address"];
        /** Format: email */
        contactEmail: string;
        /** @enum {string|null} */
        registeredAgentProvider?: "prospera_employment_solutions" | null;
        registeredAgentDetails?: {
          attn?: string;
          residentPermitNumber?: string;
          officeAddress?: components["schemas"]["Address"];
          mailingAddress?: components["schemas"]["Address"];
        } | null;
        analytics?: {
          [key: string]: unknown;
        };
      };
      referralCode?: string;
      /** Format: uri */
      redirectUrl?: string;
    };
    NaturalPerson: {
      givenName?: string;
      surname?: string;
      name?: string;
      residentPermitNumber?: string | null;
      countryOfBirth?: string | null;
      citizenships?: string[];
      dateOfBirth?: string | null;
      /** @enum {string|null} */
      sex?: "M" | "F" | null;
      address?: components["schemas"]["Address"] | null;
      phoneNumber?: string | null;
    };
    IdVerification: {
      id?: string | null;
      /** @enum {string|null} */
      type?: "veriff" | null;
      /** Format: date-time */
      date?: string | null;
      /** @enum {string|null} */
      status?: "approved" | null;
      documents?: {
        /** Format: uri */
        documentFront?: string | null;
        /** Format: uri */
        documentBack?: string | null;
        /** Format: uri */
        face?: string | null;
      };
    };
  };
  responses: {
    /** @description Validation error or precondition failure. */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Missing or invalid credential. */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Credential lacks the required scope. */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Resource does not exist or is invisible to the caller. */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Conflicting state (e.g. legal-entity name already taken). */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Rate limit exceeded. */
    RateLimited: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Server error. */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
  };
  parameters: {
    LegalEntityId: string;
    ApplicationId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
