import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { parse } from "yaml";

type OcsOption = {
  name: string;
  aliases?: string[];
};

type OcsCommand = {
  name: string;
  options?: OcsOption[];
  commands?: OcsCommand[];
};

type OcsDocument = {
  command: OcsCommand;
};

const source = await readFile("cli.ocs.yaml", "utf8");
const document = parse(source) as OcsDocument;
const words = Array.from(
  new Set([...commandWords(document.command), ...optionWords(document.command)]),
);
const outputDir = "dist/completions";

await mkdir(outputDir, { recursive: true });
await Promise.all([
  writeFile(join(outputDir, "eprospera.bash"), bash(words)),
  writeFile(join(outputDir, "eprospera.zsh"), zsh(words)),
  writeFile(join(outputDir, "eprospera.fish"), fish(words)),
  writeFile(join(outputDir, "eprospera.ps1"), powershell(words)),
]);

function commandWords(command: OcsCommand): string[] {
  return [command.name, ...(command.commands ?? []).flatMap(commandWords)];
}

function optionWords(command: OcsCommand): string[] {
  return [
    ...(command.options ?? []).flatMap((option) => [option.name, ...(option.aliases ?? [])]),
    ...(command.commands ?? []).flatMap(optionWords),
  ];
}

function shellWords(values: string[]): string {
  return values.map((value) => value.replace(/'/g, "'\\''")).join(" ");
}

function bash(values: string[]): string {
  return [
    "# Generated by scripts/gen-completions.ts.",
    "_eprospera_completions() {",
    "  local cur",
    `  cur="\${COMP_WORDS[COMP_CWORD]}"`,
    `  COMPREPLY=( $(compgen -W '${shellWords(values)}' -- "$cur") )`,
    "}",
    "complete -F _eprospera_completions eprospera",
    "",
  ].join("\n");
}

function zsh(values: string[]): string {
  return [
    "#compdef eprospera",
    "# Generated by scripts/gen-completions.ts.",
    `local -a commands=(${values.map((value) => `"${value}"`).join(" ")})`,
    "_describe 'eprospera command' commands",
    "",
  ].join("\n");
}

function fish(values: string[]): string {
  return [
    "# Generated by scripts/gen-completions.ts.",
    `complete -c eprospera -f -a '${shellWords(values)}'`,
    "",
  ].join("\n");
}

function powershell(values: string[]): string {
  const quoted = values.map((value) => `'${value.replace(/'/g, "''")}'`).join(", ");
  return [
    "# Generated by scripts/gen-completions.ts.",
    "Register-ArgumentCompleter -Native -CommandName eprospera -ScriptBlock {",
    "  param($wordToComplete)",
    `  ${quoted} | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {`,
    "    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)",
    "  }",
    "}",
    "",
  ].join("\n");
}
