import { mkdir, readdir, readFile, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { parse } from "yaml";

type OcsArgument = {
  name: string;
  required?: boolean;
  description?: string;
};

type OcsOption = OcsArgument & {
  aliases?: string[];
  arguments?: OcsArgument[];
  recursive?: boolean;
};

type OcsMetadata = {
  name: string;
  value?: unknown;
};

type OcsCommand = {
  name: string;
  description?: string;
  arguments?: OcsArgument[];
  options?: OcsOption[];
  commands?: OcsCommand[];
  exitCodes?: { code: number; description?: string }[];
  examples?: string[];
  metadata?: OcsMetadata[];
};

type OcsDocument = {
  command: OcsCommand;
};

type CommandEntry = {
  path: string[];
  command: OcsCommand;
};

const source = await readFile("cli.ocs.yaml", "utf8");
const document = parse(source) as OcsDocument;
const root = document.command;
const globalOptions = (root.options ?? []).filter((option) => option.recursive);
const exitCodes = root.exitCodes ?? [];
const commands = collectLeaves(root, [root.name]);

await writeCommandDocs(commands);

function collectLeaves(command: OcsCommand, path: string[]): CommandEntry[] {
  if (!command.commands?.length) {
    return [{ path, command }];
  }

  return command.commands.flatMap((child) => collectLeaves(child, [...path, child.name]));
}

async function writeCommandDocs(entries: CommandEntry[]): Promise<void> {
  const docsDir = "docs/commands";
  await mkdir(docsDir, { recursive: true });

  for (const file of await readdir(docsDir)) {
    if (file.endsWith(".md")) {
      await unlink(join(docsDir, file));
    }
  }

  await Promise.all(
    entries.map((entry) => writeFile(join(docsDir, `${slug(entry.path)}.md`), commandDoc(entry))),
  );
}

function commandDoc(entry: CommandEntry): string {
  const { command, path } = entry;
  const localOptions = command.options ?? [];
  const options = [...globalOptions, ...localOptions];

  return [
    `# ${path.join(" ")}`,
    "",
    "<!-- This file is generated by scripts/gen-docs.ts. Do not edit by hand. -->",
    "",
    "## Synopsis",
    "",
    `\`${synopsis(entry)}\``,
    "",
    "## Description",
    "",
    command.description ?? "No description.",
    "",
    "## Arguments",
    "",
    command.arguments?.length
      ? table(
          ["Name", "Required", "Description"],
          command.arguments.map((argument) => [
            `\`${argument.name}\``,
            argument.required ? "yes" : "no",
            argument.description ?? "",
          ]),
        )
      : "This command has no positional arguments.",
    "",
    "## Flags",
    "",
    options.length
      ? table(
          ["Flag", "Aliases", "Argument", "Description"],
          options.map((option) => [
            `\`${option.name}\``,
            (option.aliases ?? []).map((alias) => `\`${alias}\``).join(", "),
            (option.arguments ?? []).map((argument) => `\`${argument.name}\``).join(", "),
            option.description ?? "",
          ]),
        )
      : "This command has no flags.",
    "",
    "## Environment Fallbacks",
    "",
    table(
      ["Variable", "Purpose"],
      [
        ["`EPROSPERA_API_KEY`", "Bearer token when `--api-key` is not provided."],
        ["`EPROSPERA_BASE_URL`", "Override the API base URL."],
        ["`EPROSPERA_ENV=staging`", "Use the configured staging API base URL."],
        ["`XDG_CONFIG_HOME`", "Root directory for plaintext credential fallback."],
      ],
    ),
    "",
    "## Exit Codes",
    "",
    table(
      ["Code", "Meaning"],
      exitCodes.map((exitCode) => [`\`${exitCode.code.toString()}\``, exitCode.description ?? ""]),
    ),
    "",
    "## Examples",
    "",
    command.examples?.length
      ? command.examples.map((example) => `\`\`\`sh\n${example}\n\`\`\``).join("\n\n")
      : "No examples.",
    "",
    "## Metadata",
    "",
    command.metadata?.length
      ? table(
          ["Name", "Value"],
          command.metadata.map((metadata) => [
            `\`${metadata.name}\``,
            `\`${metadataValue(metadata.value)}\``,
          ]),
        )
      : "No command metadata.",
    "",
  ].join("\n");
}

function synopsis(entry: CommandEntry): string {
  const positional = (entry.command.arguments ?? []).map((argument) =>
    argument.required ? `<${argument.name}>` : `[${argument.name}]`,
  );
  return [...entry.path, ...positional, "[flags]"].join(" ");
}

function table(headers: string[], rows: string[][]): string {
  return [
    `| ${headers.map(escapeCell).join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(escapeCell).join(" | ")} |`),
  ].join("\n");
}

function metadataValue(value: unknown): string {
  if (Array.isArray(value)) {
    return value.join(", ");
  }
  if (typeof value === "object" && value !== null) {
    return JSON.stringify(value);
  }
  return String(value ?? "");
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n/g, "<br>");
}

function slug(path: string[]): string {
  return path.slice(1).join("-");
}
